CREATE TABLE 'COUNTRIES' (
    'ID' INTEGER NOT NULL,
    'ISO' TEXT NOT NULL,
    'NAME' TEXT NOT NULL,
    'NAME2' TEXT NOT NULL,
    'ISO3' TEXT DEFAULT NULL,
    'NUMCODE' INTEGER DEFAULT NULL,
    'PHONECODE' INTEGER NOT NULL,
        PRIMARY KEY ('ID'));