CREATE TABLE 'CONVERSATIONS' (
    'ID' TEXT,
    'NAME' TEXT,
        PRIMARY KEY ('ID'));

CREATE TABLE 'CONVERSATION_MEMBERS' (
    'ID' TEXT,
    'CONVERSATION_ID' TEXT,
    'NAME' TEXT,
        PRIMARY KEY ('ID', 'CONVERSATION_ID'),
        FOREIGN KEY ('CONVERSATION_ID') REFERENCES 'CONVERSATIONS' ('ID'));

CREATE TABLE 'CONVERSATION_MESSAGES' (
    'ID' TEXT,
    'CONVERSATION_ID' TEXT,
    'AUTHOR_ID' TEXT,
        PRIMARY KEY ('ID', 'CONVERSATION_ID'),
        FOREIGN KEY ('CONVERSATION_ID') REFERENCES 'CONVERSATIONS' ('ID'));