CREATE TABLE 'USERS' (
    'ID' INTEGER,
    'ACCESS_TOKEN' TEXT,
    'PUSH_TOKEN' TEXT,
    'IS_DEFAULT' INTEGER,
        PRIMARY KEY ('ID');

CREATE TABLE 'USER_PROFILES' (
    'ID' INTEGER,
    'USER_ID' INTEGER,
    'FIRST_NAME' TEXT,
    'MIDDLE_NAME' TEXT,
    'LAST_NAME' TEXT,
    'BIRTH_DATE' TEXT,
    'PHONE_NUMBER' TEXT,
    'EMAIL' TEXT,
        PRIMARY KEY ('ID', 'USER_ID'),
        FOREIGN KEY ('USER_ID') REFERENCES 'USERS' ('ID'));

CREATE TABLE 'USER_SETTINGS' (
    'ID' INTEGER,
    'USER_ID' INTEGER,
    'SMS_NOTIFICATIONS' INTEGER,
    'EMAIL_NOTIFICATIONS' INTEGER,
    'PUSH_NOTIFICATIONS' INTEGER,
        PRIMARY KEY ('ID', 'USER_ID'),
        FOREIGN KEY ('USER_ID') REFERENCES 'USERS' ('ID'));